-- Format for overwriting define values:
--
-- NDefines.NDiplomacy.MAX_CLIENT_STATES = 20
NDefines.NDiplomacy.CHANGE_RIVAL_YEARS = 15
NDefines.NDiplomacy.DISHONORABLE_PEACE_MONTHS = 1
NDefines.NDiplomacy.INFILTRATE_ADMINISTRATION_COST = 80
NDefines.NDiplomacy.MIN_RELATIONS_TO_ALLY = -150
NDefines.NDiplomacy.MONTHS_BEFORE_TOTAL_OCCUPATION = 12
NDefines.NDiplomacy.WARNING_YEARS = 10
NDefines.NGame.DAYS_BEHIND_PAUSE = 60
NDefines.NGame.DAYS_BEHIND_LOWER_SPEED = 30
NDefines.NEconomy.BANKRUPTCY_BUILDING_DESTRUCTION_THRESHOLD = 10 
NDefines.NDiplomacy.GREAT_POWER_SUBJECT_CONTRIBUTION = 0.33
NDefines.NCountry.MINIMUM_POLICY_TIME = 5 
NDefines.NCountry.PS_REDUCE_WAREXHAUSTION = 100
NDefines.NCountry.ESTATE_MIN_DISTRIBUTED_CROWNLAND = 30.1
NDefines.NCountry.LAND_FORCELIMIT_EXTRA_COST_FACTOR	= 3
NDefines.NCountry.INNOVATIVENESS_FIRST_REACHED_TECH_LEVEL = 3
NDefines.NCountry.INNOVATIVENESS_FIRST_PICKED_IDEA = 1.5
NDefines.NMilitary.CAVALRY_SPEED = 1
NDefines.NMilitary.SCORCHED_DEVASTATION_IMPACT = 25
NDefines.NMilitary.GALLEY_COMBAT_WIDTH = 1
NDefines.NGovernment.CONCENTRATE_DEVELOPMENT_CAPITAL_PROPORTION = 0.5
NDefines.NCountry.CONCENTRATE_DEVELOPMENT_DEVELOPMENT_DECREASE = 0.3
NDefines.NCountry.DISINHERIT_PRESTIGE_HIT = -35
